version: '3'
services:
  app:
    image: algo-master
    container_name: algo-master
    build: 
      context: .
      dockerfile: Dockerfile
      # no_cache: true
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - db


  db:
    image: postgres:15-alpine
    container_name: algo-master-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: algo_master